### ISSUE TITLE
需要更新 Mirai 启动时 JVM 属性

### ISSUE THREAD

**Issue by chuang02** [xzsk2/Mirai-Docker#1]
添加参数 -Dmirai.slider.captcha.supported

详见 https://docs.mirai.mamoe.net/mirai-login-solver-selenium/

否则会提示，ANDROID_PHONE 强制邀请滑块验证，并终止登陆

**Comment by sakarie9** [comment]
已更新，加入参数 `-e JAVA_OPTS="-Dmirai.slider.captcha.supported"` 启动docker

例
```
docker run --rm -it -e JAVA_OPTS="-Dmirai.slider.captcha.supported" --name="mirai" -p 8080:8080 -v $PWD/mirai/config:/app/config xzsk2/mirai-docker:latest
```
